modLoader="javafml"
loaderVersion="[32,)"
#issueTrackerURL=""
[[mods]]
modId="spleef"
version="${modVersion}"
displayName="Spleef"
authors="Jackson, bageldotjpg"
#updateJSONURL=""
#displayURL=""
#logoFile=""
description='''
A recreation of Dream's Minecraft Man Hunt/Assassin using MinecraftForge
'''

[[dependencies.spleef]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spleef]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.1]"
ordering = "NONE"
side = "BOTH"